@extends('layouts.admin')

@section('title', 'Session QR Code')

@section('header')
<div class="flex items-center justify-between">
    <div class="flex items-center">
        <a href="{{ route('admin.attendance.show', $session) }}" class="mr-4 text-gray-400 hover:text-gray-600">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
            </svg>
        </a>
        <div>
            <h1 class="text-2xl font-bold text-gray-900">Session QR Code</h1>
            <p class="text-sm text-gray-500">{{ $session->serviceType->name ?? 'Service' }} — {{ $session->service_date->format('l, M d, Y') }}</p>
        </div>
    </div>
    <div class="flex items-center space-x-3">
        <button onclick="toggleFullscreen()" class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 bg-white hover:bg-gray-50">
            <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4"/>
            </svg>
            Fullscreen
        </button>
        <button onclick="window.print()" class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 bg-white hover:bg-gray-50">
            <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/>
            </svg>
            Print
        </button>
    </div>
</div>
@endsection

@section('content')
<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">

    {{-- QR Code Panel --}}
    <div class="lg:col-span-2">
        <div class="bg-white rounded-lg shadow p-8 text-center" id="qr-panel">
            <p class="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-2">Scan to Mark Attendance</p>
            <h2 class="text-2xl font-bold text-gray-900 mb-1">{{ $session->serviceType->name ?? 'Church Service' }}</h2>
            <p class="text-gray-500 mb-6">{{ $session->service_date->format('l, F d, Y') }}
                @if($session->start_time) · {{ $session->start_time->format('g:i A') }} @endif
            </p>

            @if(!$session->allow_qr_attendance)
            <div class="mb-6 inline-flex items-center px-4 py-2 rounded-full bg-red-100 text-red-700 text-sm font-medium">
                <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636"/>
                </svg>
                QR Scanning Disabled
            </div>
            @elseif($session->status === 'closed')
            <div class="mb-6 inline-flex items-center px-4 py-2 rounded-full bg-gray-100 text-gray-700 text-sm font-medium">
                Session Closed — QR no longer active
            </div>
            @else
            <div class="mb-6 inline-flex items-center px-4 py-2 rounded-full bg-green-100 text-green-700 text-sm font-medium">
                <span class="w-2 h-2 bg-green-500 rounded-full mr-2 animate-pulse"></span>
                QR Active — Members can scan now
            </div>
            @endif

            {{-- QR Code generated by JS --}}
            <div class="flex justify-center mb-6">
                <div id="qrcode" class="p-4 bg-white border-4 border-gray-200 rounded-xl inline-block"></div>
            </div>

            <p class="text-xs text-gray-400 break-all">{{ $session->qr_code_url }}</p>

            @if($session->qr_expires_at)
            <p class="mt-2 text-xs text-orange-500">
                Expires {{ $session->qr_expires_at->format('g:i A') }}
                ({{ $session->qr_expires_at->diffForHumans() }})
            </p>
            @endif
        </div>

        {{-- Instructions --}}
        <div class="mt-6 bg-blue-50 border border-blue-100 rounded-lg p-5">
            <h4 class="text-sm font-semibold text-blue-800 mb-3">Member Instructions</h4>
            <ol class="text-sm text-blue-700 space-y-1 list-decimal list-inside">
                <li>Open the <strong>{{ \App\Helpers\SettingHelper::churchName() }} Member Portal</strong> on your phone</li>
                <li>Tap <strong>Scan Attendance</strong> in the sidebar</li>
                <li>Point your camera at this QR code</li>
                <li>Confirm to record your attendance</li>
            </ol>
        </div>
    </div>

    {{-- Controls Panel --}}
    <div class="space-y-5">

        {{-- Live scan count --}}
        <div class="bg-white rounded-lg shadow p-5">
            <h3 class="text-sm font-medium text-gray-500 mb-3">Live Scan Count</h3>
            <div class="text-center">
                <div class="text-5xl font-bold text-indigo-600" id="scan-count">{{ $qrScanCount }}</div>
                <div class="text-sm text-gray-500 mt-1">members scanned</div>
            </div>
            <button onclick="refreshCount()" class="mt-4 w-full text-center text-sm text-indigo-600 hover:text-indigo-800">
                ↻ Refresh count
            </button>
        </div>

        {{-- Session info --}}
        <div class="bg-white rounded-lg shadow p-5">
            <h3 class="text-sm font-medium text-gray-500 mb-3">Session Info</h3>
            <dl class="space-y-2 text-sm">
                <div class="flex justify-between">
                    <dt class="text-gray-500">Status</dt>
                    <dd>
                        @if($session->is_open)
                        <span class="px-2 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">Open</span>
                        @else
                        <span class="px-2 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">Closed</span>
                        @endif
                    </dd>
                </div>
                <div class="flex justify-between">
                    <dt class="text-gray-500">QR Scanning</dt>
                    <dd>
                        @if($session->allow_qr_attendance)
                        <span class="text-green-600 font-medium">Enabled</span>
                        @else
                        <span class="text-red-500 font-medium">Disabled</span>
                        @endif
                    </dd>
                </div>
                <div class="flex justify-between">
                    <dt class="text-gray-500">Total Attendance</dt>
                    <dd class="font-medium text-gray-900">{{ $session->total_attendance }}</dd>
                </div>
            </dl>
        </div>

        {{-- Actions --}}
        <div class="bg-white rounded-lg shadow p-5 space-y-3">
            <h3 class="text-sm font-medium text-gray-500 mb-1">Actions</h3>

            {{-- Toggle QR --}}
            <form action="{{ route('admin.attendance.toggle-qr', $session) }}" method="POST">
                @csrf
                <button type="submit" class="w-full px-4 py-2 text-sm font-medium rounded-lg border
                    {{ $session->allow_qr_attendance
                        ? 'border-red-300 text-red-600 hover:bg-red-50'
                        : 'border-green-300 text-green-600 hover:bg-green-50' }}">
                    {{ $session->allow_qr_attendance ? 'Disable QR Scanning' : 'Enable QR Scanning' }}
                </button>
            </form>

            {{-- Regenerate QR --}}
            <form action="{{ route('admin.attendance.regenerate-qr', $session) }}" method="POST"
                  onsubmit="return confirm('This will invalidate the current QR code. Members who have not scanned yet will need to scan the new code. Continue?')">
                @csrf
                <button type="submit" class="w-full px-4 py-2 text-sm font-medium rounded-lg border border-orange-300 text-orange-600 hover:bg-orange-50">
                    Regenerate QR Code
                </button>
            </form>

            {{-- Back to session --}}
            <a href="{{ route('admin.attendance.show', $session) }}"
               class="block w-full px-4 py-2 text-sm font-medium rounded-lg border border-gray-300 text-gray-600 hover:bg-gray-50 text-center">
                Back to Session
            </a>
        </div>
    </div>
</div>

@push('styles')
<style>
    @media print {
        .sidebar, header, .lg\:col-span-1 { display: none !important; }
        .lg\:col-span-2 { grid-column: 1 / -1 !important; }
        body { background: white !important; }
        #qr-panel { box-shadow: none !important; border: 1px solid #e5e7eb; }
    }
    #qr-panel:-webkit-full-screen { padding: 3rem; background: white; min-height: 100vh; }
    #qr-panel:-moz-full-screen    { padding: 3rem; background: white; min-height: 100vh; }
    #qr-panel:fullscreen           { padding: 3rem; background: white; min-height: 100vh; }
</style>
@endpush

@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js"></script>
<script>
const qrUrl    = @json($session->qr_code_url);
const sessionId = {{ $session->id }};

// Generate QR using qrcodejs (synchronous constructor)
new QRCode(document.getElementById('qrcode'), {
    text: qrUrl,
    width: 300,
    height: 300,
    colorDark: '#000000',
    colorLight: '#ffffff',
    correctLevel: QRCode.CorrectLevel.H
});

// Fullscreen toggle
function toggleFullscreen() {
    const el = document.getElementById('qr-panel');
    if (!document.fullscreenElement) {
        el.requestFullscreen?.() || el.webkitRequestFullscreen?.() || el.mozRequestFullScreen?.();
    } else {
        document.exitFullscreen?.() || document.webkitExitFullscreen?.() || document.mozCancelFullScreen?.();
    }
}

// Refresh scan count via AJAX
function refreshCount() {
    fetch('/admin/attendance/' + sessionId + '/qr-scan-count', {
        headers: { 'X-Requested-With': 'XMLHttpRequest', 'Accept': 'application/json' }
    })
    .then(r => r.json())
    .then(data => { document.getElementById('scan-count').textContent = data.count; })
    .catch(() => {});
}

// Auto-refresh every 15 seconds while page is visible
setInterval(() => { if (!document.hidden) { refreshCount(); } }, 15000);
</script>
@endpush
@endsection
