<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssetSeeder extends Seeder
{
    public function run(): void
    {
        $assets = [
            // Musical Instruments
            [
                'asset_code' => 'AST-MUS-001',
                'name' => 'Yamaha Keyboard PSR-E473',
                'category_id' => 1,
                'description' => 'Main worship keyboard',
                'serial_number' => 'YMH-2023-45678',
                'purchase_date' => '2023-03-15',
                'purchase_price' => 3500.00,
                'current_value' => 3150.00,
                'supplier' => 'Melcom Ghana',
                'warranty_expiry' => '2025-03-15',
                'location' => 'Main Auditorium - Stage',
                'assigned_to_ministry_id' => 5,
                'condition_status' => 'excellent',
                'status' => 'active',
                'created_by' => 1,
            ],
            [
                'asset_code' => 'AST-MUS-002',
                'name' => 'Drum Set - Premier Complete',
                'category_id' => 1,
                'description' => '5-piece drum set with cymbals',
                'serial_number' => 'PRM-2022-12345',
                'purchase_date' => '2022-06-20',
                'purchase_price' => 4000.00,
                'current_value' => 3200.00,
                'supplier' => 'Music World Accra',
                'warranty_expiry' => null,
                'location' => 'Main Auditorium - Stage',
                'assigned_to_ministry_id' => 5,
                'condition_status' => 'good',
                'status' => 'active',
                'created_by' => 1,
            ],
            
            // Sound Equipment
            [
                'asset_code' => 'AST-SND-001',
                'name' => 'Behringer X32 Digital Mixer',
                'category_id' => 2,
                'description' => '32-channel digital mixing console',
                'serial_number' => 'BHR-X32-2024-001',
                'purchase_date' => '2024-09-01',
                'purchase_price' => 8000.00,
                'current_value' => 7600.00,
                'supplier' => 'Pro Audio Ghana',
                'warranty_expiry' => '2026-09-01',
                'location' => 'Main Auditorium - Sound Booth',
                'assigned_to_ministry_id' => 7,
                'condition_status' => 'excellent',
                'status' => 'active',
                'created_by' => 1,
            ],
            [
                'asset_code' => 'AST-SND-002',
                'name' => 'JBL PRX815 Main Speakers (Pair)',
                'category_id' => 2,
                'description' => '15-inch powered PA speakers',
                'serial_number' => 'JBL-PRX-2024-002',
                'purchase_date' => '2024-09-01',
                'purchase_price' => 6000.00,
                'current_value' => 5700.00,
                'supplier' => 'Pro Audio Ghana',
                'warranty_expiry' => '2026-09-01',
                'location' => 'Main Auditorium',
                'assigned_to_ministry_id' => 7,
                'condition_status' => 'excellent',
                'status' => 'active',
                'created_by' => 1,
            ],
            [
                'asset_code' => 'AST-SND-003',
                'name' => 'Shure SM58 Microphones (Set of 6)',
                'category_id' => 2,
                'description' => 'Dynamic vocal microphones',
                'serial_number' => null,
                'purchase_date' => '2023-01-10',
                'purchase_price' => 1800.00,
                'current_value' => 1530.00,
                'supplier' => 'Pro Audio Ghana',
                'warranty_expiry' => null,
                'location' => 'Main Auditorium',
                'assigned_to_ministry_id' => 7,
                'condition_status' => 'good',
                'status' => 'active',
                'created_by' => 1,
            ],
            
            // Furniture
            [
                'asset_code' => 'AST-FRN-001',
                'name' => 'Plastic Chairs (200 pieces)',
                'category_id' => 3,
                'description' => 'White plastic chairs for congregation',
                'serial_number' => null,
                'purchase_date' => '2021-05-15',
                'purchase_price' => 6000.00,
                'current_value' => 4200.00,
                'supplier' => 'Accra Furniture Works',
                'warranty_expiry' => null,
                'location' => 'Main Auditorium',
                'assigned_to_ministry_id' => null,
                'condition_status' => 'good',
                'status' => 'active',
                'created_by' => 1,
            ],
            [
                'asset_code' => 'AST-FRN-002',
                'name' => 'Wooden Pulpit',
                'category_id' => 3,
                'description' => 'Main preaching pulpit',
                'serial_number' => null,
                'purchase_date' => '2018-08-20',
                'purchase_price' => 2500.00,
                'current_value' => 1750.00,
                'supplier' => 'Local Carpenter',
                'warranty_expiry' => null,
                'location' => 'Main Auditorium - Stage',
                'assigned_to_ministry_id' => null,
                'condition_status' => 'good',
                'status' => 'active',
                'created_by' => 1,
            ],
            
            // Electronics
            [
                'asset_code' => 'AST-ELC-001',
                'name' => 'Epson EB-X51 Projector',
                'category_id' => 4,
                'description' => 'Main projector for presentations',
                'serial_number' => 'EPS-2023-78901',
                'purchase_date' => '2023-06-01',
                'purchase_price' => 3000.00,
                'current_value' => 2400.00,
                'supplier' => 'CompuGhana',
                'warranty_expiry' => '2025-06-01',
                'location' => 'Main Auditorium',
                'assigned_to_ministry_id' => 7,
                'condition_status' => 'good',
                'status' => 'active',
                'created_by' => 1,
            ],
            [
                'asset_code' => 'AST-ELC-002',
                'name' => 'HP Desktop Computer',
                'category_id' => 4,
                'description' => 'Church office computer',
                'serial_number' => 'HP-2024-56789',
                'purchase_date' => '2024-01-15',
                'purchase_price' => 4500.00,
                'current_value' => 3600.00,
                'supplier' => 'CompuGhana',
                'warranty_expiry' => '2026-01-15',
                'location' => 'Church Office',
                'assigned_to_ministry_id' => null,
                'condition_status' => 'excellent',
                'status' => 'active',
                'created_by' => 1,
            ],
            [
                'asset_code' => 'AST-ELC-003',
                'name' => 'HP LaserJet Pro Printer',
                'category_id' => 4,
                'description' => 'Office printer for documents',
                'serial_number' => 'HP-LJ-2024-001',
                'purchase_date' => '2024-01-15',
                'purchase_price' => 1200.00,
                'current_value' => 960.00,
                'supplier' => 'CompuGhana',
                'warranty_expiry' => '2025-01-15',
                'location' => 'Church Office',
                'assigned_to_ministry_id' => null,
                'condition_status' => 'good',
                'status' => 'active',
                'created_by' => 1,
            ],
            
            // Office Equipment
            [
                'asset_code' => 'AST-OFF-001',
                'name' => 'Executive Office Desk',
                'category_id' => 8,
                'description' => 'Pastor\'s office desk',
                'serial_number' => null,
                'purchase_date' => '2020-03-10',
                'purchase_price' => 1500.00,
                'current_value' => 1050.00,
                'supplier' => 'Melcom Ghana',
                'warranty_expiry' => null,
                'location' => 'Pastor\'s Office',
                'assigned_to_ministry_id' => null,
                'condition_status' => 'good',
                'status' => 'active',
                'created_by' => 1,
            ],
        ];

        foreach ($assets as $asset) {
            DB::table('assets')->insert(array_merge($asset, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
