<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MemberSeeder extends Seeder
{
    public function run(): void
    {
        $members = [
            [
                'member_id' => 'COP-2024-00001',
                'title' => 'Elder',
                'first_name' => 'Kwame',
                'middle_name' => 'Asante',
                'last_name' => 'Mensah',
                'date_of_birth' => '1970-05-15',
                'gender' => 'male',
                'marital_status' => 'married',
                'email' => 'kwame.mensah@email.com',
                'phone_primary' => '0244123456',
                'phone_secondary' => '0201234567',
                'address' => 'House No. 15, Abirem New Town',
                'city' => 'Abirem',
                'region' => 'Eastern Region',
                'occupation' => 'Teacher',
                'employer' => 'Ghana Education Service',
                'emergency_contact_name' => 'Ama Mensah',
                'emergency_contact_phone' => '0244111222',
                'date_joined' => '2005-03-20',
                'baptism_date' => '2005-06-15',
                'baptism_type' => 'both',
                'membership_status' => 'active',
                'created_by' => 1,
            ],
            [
                'member_id' => 'COP-2024-00002',
                'title' => 'Deaconess',
                'first_name' => 'Ama',
                'middle_name' => null,
                'last_name' => 'Mensah',
                'date_of_birth' => '1975-08-22',
                'gender' => 'female',
                'marital_status' => 'married',
                'email' => 'ama.mensah@email.com',
                'phone_primary' => '0244111222',
                'phone_secondary' => null,
                'address' => 'House No. 15, Abirem New Town',
                'city' => 'Abirem',
                'region' => 'Eastern Region',
                'occupation' => 'Nurse',
                'employer' => 'Abirem Health Center',
                'emergency_contact_name' => 'Kwame Mensah',
                'emergency_contact_phone' => '0244123456',
                'date_joined' => '2005-03-20',
                'baptism_date' => '2006-04-10',
                'baptism_type' => 'both',
                'membership_status' => 'active',
                'created_by' => 1,
            ],
            [
                'member_id' => 'COP-2024-00003',
                'title' => 'Mr',
                'first_name' => 'Kofi',
                'middle_name' => 'Owusu',
                'last_name' => 'Adjei',
                'date_of_birth' => '1990-11-08',
                'gender' => 'male',
                'marital_status' => 'single',
                'email' => 'kofi.adjei@email.com',
                'phone_primary' => '0555987654',
                'phone_secondary' => null,
                'address' => 'Abirem Estate, Block C',
                'city' => 'Abirem',
                'region' => 'Eastern Region',
                'occupation' => 'Software Developer',
                'employer' => 'Tech Solutions Ltd',
                'emergency_contact_name' => 'Yaw Adjei',
                'emergency_contact_phone' => '0244555666',
                'date_joined' => '2018-01-15',
                'baptism_date' => '2018-04-20',
                'baptism_type' => 'water',
                'membership_status' => 'active',
                'created_by' => 1,
            ],
            [
                'member_id' => 'COP-2024-00004',
                'title' => 'Mrs',
                'first_name' => 'Akosua',
                'middle_name' => 'Boateng',
                'last_name' => 'Owusu',
                'date_of_birth' => '1985-02-14',
                'gender' => 'female',
                'marital_status' => 'married',
                'email' => 'akosua.owusu@email.com',
                'phone_primary' => '0209876543',
                'phone_secondary' => '0277654321',
                'address' => 'Abirem Central',
                'city' => 'Abirem',
                'region' => 'Eastern Region',
                'occupation' => 'Business Owner',
                'employer' => 'Self Employed',
                'emergency_contact_name' => 'Kweku Owusu',
                'emergency_contact_phone' => '0244777888',
                'date_joined' => '2015-09-01',
                'baptism_date' => '2016-01-10',
                'baptism_type' => 'both',
                'membership_status' => 'active',
                'created_by' => 1,
            ],
            [
                'member_id' => 'COP-2024-00005',
                'title' => 'Mr',
                'first_name' => 'Yaw',
                'middle_name' => null,
                'last_name' => 'Acheampong',
                'date_of_birth' => '1995-06-30',
                'gender' => 'male',
                'marital_status' => 'single',
                'email' => 'yaw.acheampong@email.com',
                'phone_primary' => '0241112233',
                'phone_secondary' => null,
                'address' => 'Abirem Junction',
                'city' => 'Abirem',
                'region' => 'Eastern Region',
                'occupation' => 'Student',
                'employer' => 'University of Ghana',
                'emergency_contact_name' => 'Kwabena Acheampong',
                'emergency_contact_phone' => '0244999000',
                'date_joined' => '2020-01-15',
                'baptism_date' => null,
                'baptism_type' => 'none',
                'membership_status' => 'active',
                'created_by' => 1,
            ],
            [
                'member_id' => 'COP-2024-00006',
                'title' => 'Miss',
                'first_name' => 'Adwoa',
                'middle_name' => 'Serwaa',
                'last_name' => 'Asante',
                'date_of_birth' => '1998-03-25',
                'gender' => 'female',
                'marital_status' => 'single',
                'email' => 'adwoa.asante@email.com',
                'phone_primary' => '0557778899',
                'phone_secondary' => null,
                'address' => 'Abirem New Site',
                'city' => 'Abirem',
                'region' => 'Eastern Region',
                'occupation' => 'Banker',
                'employer' => 'GCB Bank',
                'emergency_contact_name' => 'Grace Asante',
                'emergency_contact_phone' => '0244123789',
                'date_joined' => '2019-06-10',
                'baptism_date' => '2019-12-15',
                'baptism_type' => 'water',
                'membership_status' => 'active',
                'created_by' => 1,
            ],
            [
                'member_id' => 'COP-2024-00007',
                'title' => 'Deacon',
                'first_name' => 'Emmanuel',
                'middle_name' => 'Kweku',
                'last_name' => 'Frimpong',
                'date_of_birth' => '1980-12-01',
                'gender' => 'male',
                'marital_status' => 'married',
                'email' => 'emmanuel.frimpong@email.com',
                'phone_primary' => '0244556677',
                'phone_secondary' => '0201234890',
                'address' => 'Abirem Old Town',
                'city' => 'Abirem',
                'region' => 'Eastern Region',
                'occupation' => 'Farmer',
                'employer' => 'Self Employed',
                'emergency_contact_name' => 'Comfort Frimpong',
                'emergency_contact_phone' => '0244889900',
                'date_joined' => '2008-04-05',
                'baptism_date' => '2008-08-20',
                'baptism_type' => 'both',
                'membership_status' => 'active',
                'created_by' => 1,
            ],
            [
                'member_id' => 'COP-2024-00008',
                'title' => 'Mrs',
                'first_name' => 'Comfort',
                'middle_name' => null,
                'last_name' => 'Frimpong',
                'date_of_birth' => '1983-07-18',
                'gender' => 'female',
                'marital_status' => 'married',
                'email' => null,
                'phone_primary' => '0244889900',
                'phone_secondary' => null,
                'address' => 'Abirem Old Town',
                'city' => 'Abirem',
                'region' => 'Eastern Region',
                'occupation' => 'Trader',
                'employer' => 'Self Employed',
                'emergency_contact_name' => 'Emmanuel Frimpong',
                'emergency_contact_phone' => '0244556677',
                'date_joined' => '2008-04-05',
                'baptism_date' => '2009-03-15',
                'baptism_type' => 'both',
                'membership_status' => 'active',
                'created_by' => 1,
            ],
            [
                'member_id' => 'COP-2024-00009',
                'title' => 'Mr',
                'first_name' => 'Samuel',
                'middle_name' => 'Kojo',
                'last_name' => 'Tetteh',
                'date_of_birth' => '1992-09-12',
                'gender' => 'male',
                'marital_status' => 'single',
                'email' => 'samuel.tetteh@email.com',
                'phone_primary' => '0203334455',
                'phone_secondary' => null,
                'address' => 'Abirem Main Street',
                'city' => 'Abirem',
                'region' => 'Eastern Region',
                'occupation' => 'Electrician',
                'employer' => 'ECG',
                'emergency_contact_name' => 'John Tetteh',
                'emergency_contact_phone' => '0244667788',
                'date_joined' => '2021-02-28',
                'baptism_date' => '2021-06-20',
                'baptism_type' => 'water',
                'membership_status' => 'active',
                'created_by' => 1,
            ],
            [
                'member_id' => 'COP-2024-00010',
                'title' => 'Miss',
                'first_name' => 'Grace',
                'middle_name' => 'Afia',
                'last_name' => 'Appiah',
                'date_of_birth' => '2000-04-08',
                'gender' => 'female',
                'marital_status' => 'single',
                'email' => 'grace.appiah@email.com',
                'phone_primary' => '0557776655',
                'phone_secondary' => null,
                'address' => 'Akim Oda Road, Abirem',
                'city' => 'Abirem',
                'region' => 'Eastern Region',
                'occupation' => 'Student',
                'employer' => 'KNUST',
                'emergency_contact_name' => 'Mary Appiah',
                'emergency_contact_phone' => '0244112233',
                'date_joined' => '2022-08-14',
                'baptism_date' => null,
                'baptism_type' => 'none',
                'membership_status' => 'active',
                'created_by' => 1,
            ],
        ];

        foreach ($members as $member) {
            DB::table('members')->insert(array_merge($member, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
